language: node_js
node_js:
  - "0.10"
services:
  - postgresql
addons:
  postgresql: "9.3"
notifications:
  email: false
script:
  - npm run syntax
  - npm test
before_script:
  - psql -c 'create database evernodeTest;' -U postgres
  - cd test/scripts; ./create-db.sh evernodeTest; cd ../..;
after_script:
  - npm run coveralls
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/evernodeTest
    - AWS_BUCKET=sarah-evernode-test
    # AWS_SECRET_ACCESS_KEY
    - secure: "pjafxcQt7TFwoiCA++A/0TKj9nCVIon4scxxktdWadBsrPYDu8aXLAxzNNeygAERpNCXMm0/f2CouHEztuk7ae/KUugiW+u1738agZxGvucs14NkjqrfMRstN6edqzanbpLaafzecRSbAwMn3YRO+spyGpDYiy02dK/TW36TiR8="
    # AWS_ACCESS_KEY_ID
    - secure: "OMEYCf7rl3vQ1CqPJqwCc50S/PPkQePIQoHoeswl1wNstrM7CDKBblyJjJKWBGeSnqbv7M4718hPEDuOxB6Q4Qi5ZUA3plNBDKLG48L8AYjrlFk9Tm4D2wkyLwekiBca/hmpUCm8ZTjW7Genn3+3LAJ6aZ9AA8Uu0eWtCVBREU8="
